### ISSUE TITLE
abra2 v2.24  Error loading: libAbra.so

### ISSUE THREAD

**Issue by gudeqing** [dceoy/docker-bio#7]
Hi,  I am using dceoy/abra2:latest image,  but an error reported:

 Error loading: libAbra.so from : /tmp/abra2_f063b5b6-ad55-48f0-9e41-1cce6445b5c217564350054195882455
java.lang.RuntimeException: Unable to load library: libAbra.so from path [/libAbra.so] into tempdir: [/tmp/abra2_f063b5b6-ad55-48f0-9e41-1cce6445b5c217564350054195882455]

**Comment by Manuel-DominguezCBG** [comment]
I got the same issue

```
INFO    Wed Nov 08 12:21:09 GMT 2023    Abra version: 2.24
INFO    Wed Nov 08 12:21:09 GMT 2023    Abra params: [/opt/abra2/abra2.jar --in ./RACP2_6poolv6_P5_A_FINAL_mapped.bam --out ./abra.bam --ref /mainfs/wrgl/reference_files/reference_genome/gcp-public-data--broad-references/hg38/v0_masked_new_15092023/Homo_sapiens_assembly38.fasta --threads 8 --targets /scratch/mdb1c20/RACPpipeline/ref_files/amplicons_coo_v1.1.bed]
INFO    Wed Nov 08 12:21:09 GMT 2023    ABRA version: 2.24
INFO    Wed Nov 08 12:21:09 GMT 2023    input0: ./RACP2_6poolv6_P5_A_FINAL_mapped.bam
INFO    Wed Nov 08 12:21:09 GMT 2023    output0: ./abra.bam
INFO    Wed Nov 08 12:21:09 GMT 2023    regions: /scratch/mdb1c20/RACPpipeline/ref_files/amplicons_coo_v1.1.bed
INFO    Wed Nov 08 12:21:09 GMT 2023    reference: /mainfs/wrgl/reference_files/reference_genome/gcp-public-data--broad-references/hg38/v0_masked_new_15092023/Homo_sapiens_assembly38.fasta
INFO    Wed Nov 08 12:21:09 GMT 2023    num threads: 8
INFO    Wed Nov 08 12:21:09 GMT 2023    minEdgeFrequency: 0
minNodeFrequncy: 1
minContigLength: -1
minBaseQuality: 20
minReadCandidateFraction: 0.01
maxAverageRegionDepth: 1000
minEdgeRatio: 0.01

INFO    Wed Nov 08 12:21:09 GMT 2023    paired end: true
INFO    Wed Nov 08 12:21:09 GMT 2023    isSkipAssembly: false
INFO    Wed Nov 08 12:21:09 GMT 2023    useSoftClippedReads: true
INFO    Wed Nov 08 12:21:09 GMT 2023    SW scoring: [8, 32, 48, 1]
INFO    Wed Nov 08 12:21:09 GMT 2023    Soft clip params: [16, 13, 80, 15]
INFO    Wed Nov 08 12:21:09 GMT 2023    Java version: 11.0.19
INFO    Wed Nov 08 12:21:09 GMT 2023    hostname: cyan51.cluster.local
INFO    Wed Nov 08 12:21:09 GMT 2023    SG match,mismatch,gap_open_penalty,gap_extend_penalty: 8,-32,-48,-1
INFO    Wed Nov 08 12:21:09 GMT 2023    Using temp directory: /tmp/abra2_314dceda-ef90-4bbf-830a-277e41a87ce110551265396937924366
ERROR   Wed Nov 08 12:21:09 GMT 2023    Error loading: libAbra.so from : /tmp/abra2_314dceda-ef90-4bbf-830a-277e41a87ce110551265396937924366
java.lang.RuntimeException: Unable to load library: libAbra.so from path [/libAbra.so] into tempdir: [/tmp/abra2_314dceda-ef90-4bbf-830a-277e41a87ce110551265396937924366]
        at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:50)
        at abra.ReAligner.init(ReAligner.java:1627)
        at abra.ReAligner.reAlign(ReAligner.java:163)
        at abra.ReAligner.run(ReAligner.java:1810)
        at abra.Abra.main(Abra.java:12)
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Unable to load library: libAbra.so from path [/libAbra.so] into tempdir: [/tmp/abra2_314dceda-ef90-4bbf-830a-277e41a87ce110551265396937924366]
        at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:57)
        at abra.ReAligner.init(ReAligner.java:1627)
        at abra.ReAligner.reAlign(ReAligner.java:163)
        at abra.ReAligner.run(ReAligner.java:1810)
        at abra.Abra.main(Abra.java:12)
Caused by: java.lang.RuntimeException: Unable to load library: libAbra.so from path [/libAbra.so] into tempdir: [/tmp/abra2_314dceda-ef90-4bbf-830a-277e41a87ce110551265396937924366]
        at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:50)

```

**Comment by gudeqing** [comment]
@Manuel-DominguezCBG  I am using an alternative image from goalconsortium/abra2:latest, with version 2.20
